name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
on:
  pull_request:
    branches-ignore:
      - "main"

jobs:
  Checkstyle-Lint-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Validate Formatting
        run: pnpm turbo prettier:check
      - name: Validate Linting
        run: pnpm turbo lint
      - name: Pull Vercel Environment Variables
        run: pnpm vercel env pull --environment=preview --git-branch=${{ github.base_ref }} --token=${{ secrets.VERCEL_TOKEN }} .env
      - name: Pull Vercel Build Configuration
        run: pnpm vercel pull --yes --environment=preview --git-branch=${{ github.base_ref }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: pnpm vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Migration Dry Run
        run: pnpm db:migrate --dry-run
